### PR TITLE
Add unit test framework

### PR DESCRIPTION
**Pull request by davesmotleyprojects**
Add a unit test framework to the project to enhance debug capability, document expected (and unexpected) behaviors, and to prevent regressions.

### CODE REVIEW

**Comment by zarath** [comment]
Thanks, it's a great suggestion to get Unit tests in NanoVNASaver's code.
Unluckily have sourced out that SI number formatting into the SITools module.
So the right Class to test would be SITools.Value.... which isn't bound to just Hz as unit.

Woul'd you like to take a look at that class, as all RFTools.Format methods now just use that
Class?

There was an issue with successive repeating str conversation with that new class, which is already fixed. e.G.

x = Value(10, "Hz")
s1 = str(x)
s2 = str(x)
assert (s1 == s2)

Regards and 73
   Holger

**Comment by davesmotleyprojects** [comment]
Hi Holger, 
Since SITools is so new and still changing, I will wait until it is delivered to characterize it. Please be aware that there are two competing requirements for frequency formatting.
1) The frequency values for the marker data needs to be consistently sized to fit the display.
    (i.e. always 5 digits, 1.23456789MHz becomes 1.2346MHz)
2) The sweep data (Start, Stop, Center, Span) should be nicely formatted if possible, but must not lose accuracy.
    (i.e. 5 digits if possible, otherwise, as many digits as needed, 1.23456789MHz stays 1.23456789MHz, but 1.20000000MHz can become 1.2000MHz)  
- Dave

**Comment by davesmotleyprojects** [comment]
Hi Holger, 
I was making an assumption that you were still working on the SITools file. I should have asked. If you have already moved on to other changes and the SITools file is stable, I can start looking at the Format function right away. I didn't want to be making changes to things that you were actively working on. I can also ensure that the sweep controls maintain accuracy, if you haven't already done that. Let me know if you are ready for me to get started.  
Cheers, 
Dave

**Comment by zarath** [comment]
You could easily achieve higher displayed accuracy by specifying more digits to the format settings of the Value object.
The value.attribute has still the full precision of the underlying number type (float if parsed via parse method) 
I think one should discuss the layout of the sweep inputs, as with 1Hz resolution the resulting 10 character long string representation wouln'd fit in with char size of 8 on an HD display. This can lead to error prone readings and breaks screenshots.
Even with max_nr_digits=4 one can input 123456789Hz  and that value will be used internally.

**Comment by davesmotleyprojects** [comment]
The functionality provided by the formatSweepFrequency function that was replaced 5 days ago, is no longer being provided by the call to the SITools Value object. The previous functionality reduced the printed output to only 2 decimal places, _as long as there was no loss of precision_. (Note the use of mindigits vs. maxdigits) The previous functionality was better than forcing the display to always equal a certain number of digits. Forcing the display to always equal 10 digits, would not be desirable for someone that only wants a 6-10MHz sweep for the reasons that you point out, but only displaying 14.317MHz to 14.500MHz is going to be confusing to someone that manually entered 14.317125MHz to 14.500750MHz. Since you appear to still be working on the file, can you please look into finding a solution that maintains the previous functionality? Thanks.

**Comment by mihtjel** [comment]
For the sweep start/stop/center/span inputs *specifically*, I'd like them to have the required number of digits for full accuracy, down to 1Hz resolution. In most cases I would expect users to enter something like "14MHz", in which case no additional digits are necessary, but if you are sweeping a narrow filter, it should be able to show however many digits are required.

I do want to change the layout to make the fields and values fit easier on more monitor types. Roughly: Reducing the space taken up by the "reference" box, moving TDR to the marker data panel, and putting start/stop/center/span on separate lines to increase width.

**Comment by zarath** [comment]
If a proposal in pull request #98 

In [17]: RFTools.formatSweepFrequency(144300000)                                                                                                                               
Out[17]: '144.3MHz'
In [18]: RFTools.formatSweepFrequency(144300050)                                                                                                                               
Out[18]: '144.30005MHz'
In [19]: RFTools.formatSweepFrequency(144300051)                                                                                                                               
Out[19]: '144.300051MHz'
In [20]: RFTools.formatSweepFrequency(144000000)                                                                                                                               
Out[20]: '144MHz'

**Pull request merged**
