### PR TITLE
For better snp(touchstone) file compatibility #99

### PR DESCRIPTION
**Pull request by d51r3verse**
Better compatibility
Also dB/Angle type supported

### CODE REVIEW

**Comment by mihtjel** [comment]
Hi,
thank you for your contribution!

Please direct any pull requests towards the Development branch. There's already a new version of the Touchstone reading in there, and it's due to be released when the next version is ready.

**Comment by zarath** [comment]
Thanks for you're affords. But as @mihtjel already says, he likes to get merge request agains Development branch, where this request cannot apply anymore as I was already rewriting
the parser to conform with Touchstone 1.1 specs.

This issue is resolved with #106 .

**Comment by mihtjel** [comment]
> This issue is resolved with #106 .

Is magnitude/angle support also (still) in the new version?

**Comment by zarath** [comment]
> > This issue is resolved with #106 .
> 
> Is magnitude/angle support also (still) in the new version?

yes of course :-)

https://github.com/mihtjel/nanovna-saver/blob/68acf7d51491ff90ec89b03c76f47c5ce88449bf/NanoVNASaver/Touchstone.py#L135-L146

**Comment by zarath** [comment]
@d51r3verse 
Thanks for your additions and thought's.
Is it ok for you to close this PR?

**Comment by d51r3verse** [comment]
Sorry, I did not noticed already you improved snp file improvements.
I will close my PR.

**Pull request closed without merging**
