### PR TITLE
Use shortend frequency values in sweep input

### PR DESCRIPTION
**Pull request by zarath**
I've modified the RFTools frequency parser to cope with more SI prefixes and
added a new formatter to shorten frequency values for easier human readabilities.

73
   DG5DBH

### CODE REVIEW

**Comment by mihtjel** [comment]
Hello,
thank you very much! These look like good changes!

The Qt version is deliberately set to 5.11.2 because of issues building executables for Windows. I'm open to changing it, but I would prefer to do so as a separate pull request (or rather, when I'm ready for it for the build environment).

I would prefer for the changes to be pushed to the Development branch, and not to master, as I make and test updates in Development before they are officially released. I'm not entirely sure I can do this from the GitHub interface, though.

**Comment by zarath** [comment]
Thanks, I think I can clean up the code a little bit, and make it somewhat more general.

It shares much funtionality with formatFrequency and formatShort... so i think i can make it compatible to unify code

**Comment by mihtjel** [comment]
Thanks, your efforts are much appreciated!

**Comment by zarath** [comment]
I will wait for the merge or cherrypick until I commit further patches.

I have modified RFTools a little bit to substiute formatShortFrequency.
It is not 100% compatible, as i would print decimals for values < 100.
As an advantage the overall length of the string would be more consistent.

I wonder why there is the change from kHz to Mhz if frequency is
>= 10Mhz in format frequency. Also the resulting string is one
char longer for values => 1Mhz and < 10Mhz as for all other values.
With my changed routine below you get nearly the same results with 
maxdigits set to 7 respective 8.

https://github.com/mihtjel/nanovna-saver/compare/Development...zarath:Development#diff-67ee5872237b70b12d472cf1b706f198

**Comment by mihtjel** [comment]
Probably just a bug that never got discovered/fixed ;-) I will try out your code probably tomorrow. It looks a lot neater than what I had already done :-)

**Pull request merged**
