### PR TITLE
Feature/refactor marker

### PR DESCRIPTION
**Pull request by zarath**
Hi Rune,

I've refactored a lot of the Marker formatting.
As an effect not all representations are 100% the same
as in previous Version, but more consistent.
Especially  negative inductance and capacity
is now shown as - pF resp. - nH.
Please tell if you're fine with it. If not, I can change that
easily.

As I now don't test for zero devision in the calculation itself,
it could be possible that exceptions will be thrown. - At least
with my available test data, this didn't happened.
If some occur I'ld like to catch them in the format functions.

### CODE REVIEW

**Comment by mihtjel** [comment]
Hi Holger,
the negative inductance/capacitance values are shown on purpose when displaying the specific inductance/capacitance values - otherwise, the reactance field should be shown. :-)

**Comment by zarath** [comment]
> Hi Holger,
> the negative inductance/capacitance values are shown on purpose when displaying the specific inductance/capacitance values - otherwise, the reactance field should be shown. :-)

Yes, the reactance field switches automatically from Henry to Farad ... that's clear.
So should I readd negative vals in the capacitve / inductance fields?

**Comment by mihtjel** [comment]
Yes, exactly. :-)

**Comment by zarath** [comment]
> Yes, exactly. :-)

Fixed.

**Pull request merged**
